### ISSUE TITLE
Contrast in header

### ISSUE THREAD

**Issue by k0nserv** [danger/design#1]
As mentioned briefly previously I find the nav hard to read due to the contrast of the green in the background and the white text. It also didn't occur to me immediately that it was a header with clickable links.

![image](https://cloud.githubusercontent.com/assets/1333960/16591900/038560a2-42d6-11e6-877b-0febb6f42ffa.png)

Pretty small detail, but it might be interesting to consider if there's a way to improve this. The contrast ratio between the green and the white is [1.3](https://leaverou.github.io/contrast-ratio/#white-on-hsl%28144%2C%20100%25%2C%2065%25%29)

cc @orta

**Comment by orta** [comment]
It's on my TODO to add some shadowing there, or an outline, not really sure

**Comment by k0nserv** [comment]
:+1:

**Comment by orta** [comment]
Fixed
